site_name: bulletty - TUI RSS Reader
site_url: https://bulletty.croci.dev/
repo_url: https://github.com/crocidb/bulletty
repo_name: crocidb/bulletty

theme:
  name: material
  logo: img/bulletty.png
  favicon: img/bulletty.png
  features:
      - navigation.tabs
  icon:
      logo: material/rss-box
  palette:
    scheme: slate
    primary: black
    accent: amber
  show_title: true
  show_stargazers: true
  font:
    text: Roboto

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite
  - admonition

nav:
  - Home: 'index.md'
  - Install: 'install.md'
  - Docs:
    - CLI Reference: 'docs/cli_reference.md'
    - Config: 'docs/config.md'
    - Themes: 'docs/themes.md'
    - Hooks: 'docs/hooks.md'
    - Contributing: 'contributing.md'
    - Reference: 'docs/reference.md'
